// tailwind.config.js
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#5727a6',
        'inverse-surface': '#322f37',
        'secondary-container': '#cfe6f2',
        'error-container': '#ffdad6',
        'surface-bright': '#fef7ff',
        'primary-fixed-dim': '#d3bbff',
        outline: '#7b7484',
        'primary-container': '#673ab6',
        'on-secondary-fixed-variant': '#354a53',
        tertiary: '#00483d',
        'on-tertiary-fixed': '#00201a',
        'on-primary': '#ffffff',
        'surface-container-high': '#ede6f1',
        'on-tertiary-container': '#4ce3c7',
        'surface-container-highest': '#e7e0eb',
        primary: '#673ab6',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed': '#cfe6f2',
        'on-surface': '#1d1a22',
        'inverse-primary': '#d3bbff',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#44ddc1',
        'on-tertiary-fixed-variant': '#005145',
        'on-secondary-container': '#526772',
        'on-background': '#1d1a22',
        'on-primary-fixed': '#260059',
        'surface-tint': '#673ab6',
        'surface-container-low': '#f9f1fc',
        'primary-fixed': '#ebddff',
        'inverse-on-surface': '#f6eef9',
        'secondary-fixed-dim': '#b4cad6',
        secondary: '#4c616c',
        'on-error-container': '#93000a',
        'tertiary-container': '#006254',
        background: '#fef7ff',
        'on-secondary-fixed': '#071e27',
        'tertiary-fixed': '#68fadd',
        'surface-variant': '#e7e0eb',
        'on-error': '#ffffff',
        'outline-variant': '#ccc3d5',
        'on-surface-variant': '#4a4453',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#d8c1ff',
        'surface-container': '#f3ebf6',
        surface: '#fef7ff',
        'surface-dim': '#dfd7e3',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
